### ISSUE TITLE
Mac编译测试

### ISSUE THREAD

**Issue by Emonli** [Predidit/Kazumi#114]
### issue 内容

mac编译了1.2.5版本，打开软件后显示(连接错误，请检查网络设置)
是在Q&A里面的关键特性不支持的问题吗
并且在mac里的win虚拟机里安装win版kazumi也是同样问题
没接触过dart,看不懂代码 T_T
编译别的版本直接报错，可能是我的问题
<img width="799" alt="p1" src="https://github.com/user-attachments/assets/15a8c14d-3b4d-4e89-88a6-ba92dab4042f">
<img width="800" alt="p2" src="https://github.com/user-attachments/assets/9af84153-cea7-4a96-88d6-91747c7c9bbd">
<img width="1440" alt="p3" src="https://github.com/user-attachments/assets/af27cf5f-f5e7-4394-a401-53349d65c9da">

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by Predidit** [comment]
MacOS 的应用需要声明权限。

对应描述文件在 macos/Runner/Release.entitlements 和 macos/Runner/DebugProfile.entitlements 

要在这两个文件里声明应用需要网络权限

描述应该是

```
	<key>com.apple.security.network.client</key>
	<true/>
```

这样可以让编译产物正确联网并显示瀑布流。

就像README文件里提到的那样，目前 flutter 稳定通道缺乏对 MacOS 的 PlatformView 和 Webview 的支持。所以编译产物目前是无法播放视频的。

如果一定要现在就用上 macOS 版本的 kazumi 的话。将本地的 flutter 工具链切换到 master，这是目前最新的 flutter 开发版本，已经包含和 macOS 的支持。并且在工程文件的 pubspec.yaml 中通过依赖覆写

```
dependency_overrides:
  webview_flutter_wkwebview:
    git:
      url: https://github.com/stuartmorgan/packages
      path: packages/webview_flutter/webview_flutter_wkwebview
      ref: webview-macos
```

切换 webview_flutter 库到 master 版本。然后运气好的话能编译出可执行文件。(因为 flutter 开发版本并不稳定)
